### PR TITLE
fix: maps are invariant on keys and values

### LINKED ISSUE #318: odd "got 'type', expected {}" in map declaration
example:
```
local map: {boolean:{number}} = {
	[true] = {},
}
print_type(map)
```
```
$ tl check blah.tl
({boolean : {number}})
========================================
2 errors:
blah.tl:2:22: in local declaration: map: got {number}, expected {}
blah.tl:5:1: unknown variable: print_type
```
This only seems to happen when the keys are of a certain type. For example, `number` keys are just fine
```
local map: {number:{number}} = {
	[3] = {},
}
```
type checks just fine

Additionally, it seems like some `same_type`/`is_a` arguments are in the wrong order somewhere as the intent here seems like it should be `got {}, expected {number}`

### PR DESCRIPTION
**Pull request by hishamhm**
Fixes #318.

### CODE REVIEW

**Comment by FourierTransformer** [comment]
Can confirm this fixed the one issue described in #317 !

**Comment by hishamhm** [comment]
@euclidianAce Looks like this fixes #318 as well, any concerns on merging this one?

**Comment by euclidianAce** [comment]
@hishamhm Looks good to me :+1:

**Comment by hishamhm** [comment]
Thank you for the feedback! Merged!

**Pull request merged**
